# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class ImageServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageRotation = channel.unary_unary(
                '/ImageServer/ImageRotation',
                request_serializer=image__pb2.RotateImage.SerializeToString,
                response_deserializer=image__pb2.SampleImage.FromString,
                )
        self.ApplyFilter = channel.unary_unary(
                '/ImageServer/ApplyFilter',
                request_serializer=image__pb2.SampleImage.SerializeToString,
                response_deserializer=image__pb2.SampleImage.FromString,
                )


class ImageServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageRotation(self, request, context):
        """Rotate an image based on the provided rotation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyFilter(self, request, context):
        """Apply a mean filter to the image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageRotation': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageRotation,
                    request_deserializer=image__pb2.RotateImage.FromString,
                    response_serializer=image__pb2.SampleImage.SerializeToString,
            ),
            'ApplyFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyFilter,
                    request_deserializer=image__pb2.SampleImage.FromString,
                    response_serializer=image__pb2.SampleImage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageRotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageServer/ImageRotation',
            image__pb2.RotateImage.SerializeToString,
            image__pb2.SampleImage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageServer/ApplyFilter',
            image__pb2.SampleImage.SerializeToString,
            image__pb2.SampleImage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
