# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_procedure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15image_procedure.proto\";\n\x08\x42\x36\x34Image\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"+\n\nPrediction\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\x12\x0c\n\x04mean\x18\x05 \x01(\x02\x32\x39\n\x0eImageProcedure\x12\'\n\x0bImageMeanWH\x12\t.B64Image\x1a\x0b.Prediction\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_procedure_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_B64IMAGE']._serialized_start=25
  _globals['_B64IMAGE']._serialized_end=84
  _globals['_PREDICTION']._serialized_start=86
  _globals['_PREDICTION']._serialized_end=129
  _globals['_IMAGEPROCEDURE']._serialized_start=131
  _globals['_IMAGEPROCEDURE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
