# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"I\n\x0bSampleImage\x12\r\n\x05\x63olor\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\xa2\x01\n\x0bRotateImage\x12\'\n\x08rotation\x18\x01 \x01(\x0e\x32\x15.RotateImage.Rotation\x12\x1b\n\x05image\x18\x02 \x01(\x0b\x32\x0c.SampleImage\"M\n\x08Rotation\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nNINETY_DEG\x10\x01\x12\x12\n\x0eONE_EIGHTY_DEG\x10\x02\x12\x13\n\x0fTWO_SEVENTY_DEG\x10\x03\x32\x65\n\x0bImageServer\x12+\n\rImageRotation\x12\x0c.RotateImage\x1a\x0c.SampleImage\x12)\n\x0b\x41pplyFilter\x12\x0c.SampleImage\x1a\x0c.SampleImageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SAMPLEIMAGE']._serialized_start=15
  _globals['_SAMPLEIMAGE']._serialized_end=88
  _globals['_ROTATEIMAGE']._serialized_start=91
  _globals['_ROTATEIMAGE']._serialized_end=253
  _globals['_ROTATEIMAGE_ROTATION']._serialized_start=176
  _globals['_ROTATEIMAGE_ROTATION']._serialized_end=253
  _globals['_IMAGESERVER']._serialized_start=255
  _globals['_IMAGESERVER']._serialized_end=356
# @@protoc_insertion_point(module_scope)
